language: csharp
solution: WindowsFormsApplication1.sln
install:
  - nuget restore WindowsFormsApplication1.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WindowsFormsApplication1.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe WindowsFormsApplication1Tests/bin/Debug/WindowsFormsApplication1Tests.dll
